// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj879SBQ3yS3I_O_6djmvrqLVsX-cqjms',
    appId: '1:304711399498:web:3c59511c5bbb4d1effceb3',
    messagingSenderId: '304711399498',
    projectId: 'ai-for-loans',
    authDomain: 'ai-for-loans.firebaseapp.com',
    storageBucket: 'ai-for-loans.firebasestorage.app',
    measurementId: 'G-DVXPMHDN49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbTGKaKa7cogbX6xAAhkF-h5ckS26B98c',
    appId: '1:304711399498:android:d2a4c1be7bd4ce57ffceb3',
    messagingSenderId: '304711399498',
    projectId: 'ai-for-loans',
    storageBucket: 'ai-for-loans.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr5EzxbcRkWBYULo8JTlHiJ3jtRiJNJE8',
    appId: '1:304711399498:ios:6ba7b72b9f26bc97ffceb3',
    messagingSenderId: '304711399498',
    projectId: 'ai-for-loans',
    storageBucket: 'ai-for-loans.firebasestorage.app',
    iosClientId: '304711399498-ojbn72mdihqrb330qoeesnm3hi8u71h9.apps.googleusercontent.com',
    iosBundleId: 'com.ronith.loanai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr5EzxbcRkWBYULo8JTlHiJ3jtRiJNJE8',
    appId: '1:304711399498:ios:6ba7b72b9f26bc97ffceb3',
    messagingSenderId: '304711399498',
    projectId: 'ai-for-loans',
    storageBucket: 'ai-for-loans.firebasestorage.app',
    iosClientId: '304711399498-ojbn72mdihqrb330qoeesnm3hi8u71h9.apps.googleusercontent.com',
    iosBundleId: 'com.ronith.loanai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj879SBQ3yS3I_O_6djmvrqLVsX-cqjms',
    appId: '1:304711399498:web:82304e535d734a1effceb3',
    messagingSenderId: '304711399498',
    projectId: 'ai-for-loans',
    authDomain: 'ai-for-loans.firebaseapp.com',
    storageBucket: 'ai-for-loans.firebasestorage.app',
    measurementId: 'G-RG52NYX1EM',
  );

}